kind: Namespace
apiVersion: v1
metadata:
  name: web-app
---
kind: Service
apiVersion: v1
metadata:
  name: web-app-service
  namespace: web-app
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
