language: node_js
node_js:
  - node

os:
  - linux

stages:
  - name: test
  - name: build

jobs:
  fast_finish: true
  include:
    - stage: test
      name: 'Frontend Tests'
      script:
        - yarn test
    - stage: build
      name: 'Frontend Build'
      script:
        - yarn build
