language: node_js
node_js:
  - node

os:
  - linux

stages:
  - name: test
  - name: build

jobs:
  include:
    - name: 'Tests'
      stage: test
      script:
        - yarn test
    - name: 'Build'
      stage: build
      script:
        - yarn build
