language: node_js
node_js:
  - node

os:
  - linux

stages:
  - name: test
  - name: build
  - name: deploy
    if: branch = master AND type = push

jobs:
  fast_finish: true
  include:
    - stage: test
      name: 'Frontend Tests'
      script:
        - yarn test
    - stage: build
      name: 'Frontend Build'
      script:
        - yarn build
    - stage: deploy
      name: 'Deploy Athenian Webapp'
      script:
        - docker build --tag=athenian-app:$TRAVIS_COMMIT .
        #- docker push athenian-app:$TRAVIS_COMMIT
