apiVersion: v1
kind: Secret
metadata:
  name: controller-secret
  namespace: web-app
type: Opaque
data:
  google-credentials: {{google-credentials}}
  google-project-name: {{google-project-name}}
  google-subscription-id: {{google-subscription-id}}
